In [1]:
# Thank you Vincent!

# Using Deep Learning and Machine Learning to predict malicious urls
# https://github.com/joshsaxe/eXposeDeepNeuralNetwork

In [2]:
# Load the data
from urlparse import urlparse
import pandas as pd
urls = pd.read_json("data/url_nn.json")
print urls.shape
urls['string'] = "http://" + urls['string']

(5000, 3)


In [53]:
urls.head(50)

pred                                             string  truth
0   1.574204e-05                      http://startbuyingstocks.com/      0
1   1.840909e-05                                  http://qqcvk.com/      0
2   1.842080e-05                          http://432parkavenue.com/      0
3   7.954729e-07                             http://gamefoliant.ru/      0
4   3.239338e-06                                    http://orka.cn/      0
5   3.043137e-04                         http://media2.mercola.com/      0
6   4.107331e-37  http://ping.chartbeat.net/ping?h=sltrib.com&p=...      0
7   1.664497e-07                          http://stephensteels.com/      0
8   1.400715e-05                                 http://kbd-eko.pl/      0
9   2.273991e-05                              http://ceskaposta.cz/      0
10  1.874393e-07                              http://accessmgt.com/      0
11  3.447522e-06                                http://khumbah.com/      0
12  1.621475e-13              http://www.ntti3.com/test/ibyhvpewne/      0
13  3.036098e-06                    http://www.rolstoel-op-maat.nl/      0
14  5.280865e-03                      http://signal2.fractime.info/      0
15  3.703047e-06                               http://uhma-bike.pl/      0
16  7.609874e-06                                   http://34c.info/      0
17  2.662802e-06                      http://shipmatescollaroy.com/      0
18  1.779410e-20        http://l.ooyala.com/verify?ts=1462457649773      0
19  1.012301e-21  http://go.ads2rtb.com/?r=/mb/han&zoneid=473887...      0
20  0.000000e+00  http://adstrx.com/?a=7118&c=66298&s1=1401a9fe-...      0
21  2.099201e-05                             http://pcdnetwork.org/      0
22  1.075840e-05                               http://cabrable.com/      0
23  7.987081e-15              http://www.ntti3.com/test/ijjurfwyns/      0
24  7.667293e-09  http://idsync.rlcdn.com/420486.gif?partner_uid...      0
25  5.252930e-11                             http://data-max.co.jp/      0
26  5.286393e-14              http://www.ntti3.com/test/gkxxhvuogi/      0
27  1.244663e-12              http://www.ntti3.com/test/geolmprugr/      0
28  2.779641e-05                                   http://mocar.me/      0
29  1.966303e-09                                http://teen-pix.ru/      0
30  1.795326e-07                               http://kasen-ep.com/      0
31  2.189027e-08                              http://poezenrijk.nl/      0
32  5.592712e-14              http://www.ntti3.com/test/gxrgveppdb/      0
33  2.263402e-15  http://pull.db-gmresearch.com/p/690-706b/71178...      0
34  7.680717e-11  http://www1.cdn.sherdog.com/image_crop/72/72/_...      0
35  4.260282e-11                               http://ap-com.co.jp/      0
36  1.442061e-36  http://cdn.icloud-content.com/p/1/asaddasimwcl...      0
37  5.846325e-05                             http://drivebueno.com/      0
38  1.059652e-15              http://www.ntti3.com/test/eyksiyidtc/      0
39  2.831796e-37  http://log.adaptv.advertising.com/log?3a=progr...      0
40  1.296106e-06                                 http://amanme.com/      0
41  0.000000e+00  http://qa.eosadvantage.com/httpmodule/estimate...      0
42  3.888675e-05                                http://bmcebank.ma/      0
43  2.152546e-06                    http://automotivecomponents.lu/      0
44  2.375437e-05                                http://alicili.org/      0
45  2.124549e-34  http://bttrack.com/engagement/event?input=%7b%...      0
46  1.863335e-05                             http://32masseydr.com/      0
47  1.879376e-07                        http://yoursantander.co.uk/      0
48  1.000000e+00  http://decolider.com/system/database/konto-ver...      1
49  8.976840e-01  http://spiritofarabia.com/skin/frontend/defaul...      1

In [58]:
urls[urls['truth']==1].head()

pred                                             string  truth
48   1.000000  http://decolider.com/system/database/konto-ver...      1
49   0.897684  http://spiritofarabia.com/skin/frontend/defaul...      1
64   0.060241                  http://sinanoori.com/downloader/c      1
86   0.333332                   http://castletownglass.com/ed/ed      1
137  0.632627          http://eternityscarves.com/harchaedition/      1

In [4]:
X, y = urls['string'], urls['truth']

In [5]:
X.head()  # look at X

0    http://startbuyingstocks.com/
1                http://qqcvk.com/
2        http://432parkavenue.com/
3           http://gamefoliant.ru/
4                  http://orka.cn/
Name: string, dtype: object

In [6]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: truth, dtype: int64

In [7]:
y.value_counts(normalize=True)  # get our null accuracy because we are interested in prediction

0    0.9694
1    0.0306
Name: truth, dtype: float64

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
# EXERCISE

# Create a fucntion called custom_tokenizer that takes in a string and outputs a list of tokens of the string.
# You may choose how few or how many tokens you can choose to return.

# eg.
from urlparse import urlparse
import re
def custom_tokenizer(str):
    final = []
    final.extend(re.compile("[(\:\/\/).\-?&]").split(str))
    return final

print custom_tokenizer('https://google.com')

print custom_tokenizer('https://google-so-not-fake.com?fake=False&seriously=True')



['https', '', '', 'google', 'com']
['https', '', '', 'google', 'so', 'not', 'fake', 'com', 'fake=False', 'seriously=True']


In [20]:
import re

def custom_tokenizer(string):
    final = []
    tokens = [a for a in list(urlparse(string)) if a]
    for t in tokens:
        final.extend(re.compile("[.-]").split(t))
    return final

In [21]:
custom_tokenizer('google.com')

['google', 'com']

In [22]:
custom_tokenizer('https://google.com')

['https', 'google', 'com']

In [23]:
custom_tokenizer('https://google-so-not-fake.com?fake=False&seriously=True')

['https', 'google', 'so', 'not', 'fake', 'com', 'fake=False&seriously=True']

In [24]:
vect = CountVectorizer(tokenizer=custom_tokenizer)

In [25]:
vect.fit_transform(X)

<5000x11502 sparse matrix of type '<type 'numpy.int64'>'
	with 31293 stored elements in Compressed Sparse Row format>

In [26]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr_pipe = Pipeline([('vect', vect), ('model', lr)])

In [27]:
from sklearn.model_selection import cross_val_score, GridSearchCV, train_test_split

In [28]:
scores = cross_val_score(lr_pipe, X, y, cv=5)

scores.mean()  # not good enough!!

0.98000238400238404

In [29]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

rf_pipe = Pipeline([('vect', vect), ('model', RandomForestClassifier(n_estimators=500))])
scores = cross_val_score(rf_pipe, X, y, cv=5)

scores.mean()  # not as good

0.98080278480278482

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

from sklearn.metrics import confusion_matrix

rf_pipe.fit(X_train, y_train)

preds = rf_pipe.predict(X_test)
print confusion_matrix(y_test, preds)  # hmmmm

[[1207    0]
 [  29   14]]


In [48]:
probs = rf_pipe.predict_proba(X_test)[:,1]

In [49]:
import numpy as np
for thresh in [.1, .2, .3, .4, .5, .6, .7, .8, .9]:
    preds = np.where(probs >= thresh, 1, 0)
    print thresh
    print confusion_matrix(y_test, preds)
    print

0.1
[[1202    5]
 [  21   22]]

0.2
[[1206    1]
 [  24   19]]

0.3
[[1207    0]
 [  26   17]]

0.4
[[1207    0]
 [  28   15]]

0.5
[[1207    0]
 [  29   14]]

0.6
[[1207    0]
 [  30   13]]

0.7
[[1207    0]
 [  30   13]]

0.8
[[1207    0]
 [  31   12]]

0.9
[[1207    0]
 [  31   12]]



In [50]:
from keras.utils.np_utils import to_categorical
y_train_dummy = to_categorical(y_train)
num_classes = y_train_dummy.shape[1]
y_test_dummy = to_categorical(y_test)

Using TensorFlow backend.


In [51]:
from keras.models import Model
from keras.layers import Dense, Dropout, Activation
from keras.models import Sequential
from keras.models import Model
from keras.optimizers import SGD

def mlp_model(input_layer, num_classes, optimizer="adam", epochs=25):
    model = Sequential()
    model.add(Dense(1024, input_dim=input_layer))
    model.add(Activation('relu'))
    model.add(Dropout(0.25))
    
    model.add(Dense(1024, input_dim=input_layer))
    model.add(Activation('relu'))
    model.add(Dropout(0.25))
    
    model.add(Dense(1024))
    model.add(Activation('relu'))
    model.add(Dropout(0.25))
    
    model.add(Dense(num_classes, activation='softmax'))

    epochs = epochs
    lrate = 0.01
    decay = lrate/epochs
    sgd = SGD(lr=lrate, momentum=0.9, decay=decay, nesterov=False)


    model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
    return model

In [52]:
num_epochs = 25

vect = CountVectorizer(tokenizer=custom_tokenizer)

X_train_dtm = vect.fit_transform(X_train).toarray()
X_test_dtm = vect.transform(X_test).toarray()
model = mlp_model(len(vect.get_feature_names()), num_classes, epochs=num_epochs)

print model.summary()

# Fit the model
model.fit(X_train_dtm, y_train_dummy, validation_data=(X_test_dtm, y_test_dummy), batch_size=32, nb_epoch=num_epochs)
# Final evaluation of the model

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1024)              9187328   
_________________________________________________________________
activation_1 (Activation)    (None, 1024)              0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 1024)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 1024)              1049600   
_________________________________________________________________
activation_2 (Activation)    (None, 1024)              0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 1024)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 1024)              1049600   
__________

/Users/ronliu/anaconda/lib/python2.7/site-packages/keras/models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Train on 3750 samples, validate on 1250 samples
Epoch 1/25
3750/3750 [==============================] - 19s - loss: 0.1785 - acc: 0.9605 - val_loss: 0.1337 - val_acc: 0.9656
Epoch 2/25
3750/3750 [==============================] - 19s - loss: 0.1143 - acc: 0.9707 - val_loss: 0.1177 - val_acc: 0.9656
Epoch 3/25
3750/3750 [==============================] - 19s - loss: 0.1019 - acc: 0.9707 - val_loss: 0.1033 - val_acc: 0.9656
Epoch 4/25
3750/3750 [==============================] - 19s - loss: 0.0901 - acc: 0.9707 - val_loss: 0.0919 - val_acc: 0.9656
Epoch 5/25
3750/3750 [==============================] - 19s - loss: 0.0803 - acc: 0.9707 - val_loss: 0.0823 - val_acc: 0.9656
Epoch 6/25
3750/3750 [==============================] - 19s - loss: 0.0681 - acc: 0.9717 - val_loss: 0.0732 - val_acc: 0.9752
Epoch 7/25
3750/3750 [==============================] - 19s - loss: 0.0591 - acc: 0.9781 - val_loss: 0.0701 - val_acc: 0.9768
Epoch 8/25
3750/3750 [==============================] - 19s - loss: 0.

In [189]:
scores = model.evaluate(X_test_dtm, y_test_dummy, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Accuracy: 98.40%


In [190]:
model.predict(vect.transform(['http://creditscore.com/', 'http://acharefacil.com.br/app/webroot/js/latestfnb/']).toarray())

array([[  9.99973536e-01,   2.64957744e-05],
       [  3.43389392e-01,   6.56610668e-01]], dtype=float32)

In [191]:
probs = model.predict(vect.transform(X_test).toarray())[:,1]
preds = probs >= .5
print confusion_matrix(y_test, preds)

[[1213    1]
 [  19   17]]


In [192]:
probs = rf_pipe.predict_proba(X_test)[:,1]
preds = probs >= .5
print confusion_matrix(y_test, preds)

[[1213    1]
 [  24   12]]


In [193]:
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier

In [194]:
nn_pipe = Pipeline([('vect', vect), ('model', MLPClassifier())])
scores = cross_val_score(nn_pipe, X, y, cv=5)

scores.mean()  # better I guess..

0.98420158720158724

In [195]:
nn_pipe.fit(X_train, y_train)
probs = nn_pipe.predict_proba(X_test)[:,1]
preds = probs >= .5
print confusion_matrix(y_test, preds)

[[1213    1]
 [  20   16]]


In [196]:
false_negatives = X_test[(preds==0) & (y_test==1)]  # show the false positives, the urls that "got through"

In [202]:
list(false_negatives)

[u'http://instalacionesmarmenor.com/instt/',
 u'http://datatech-ma.com/imagens/autorizados/wwww_dotz.com/acumulo_de_pontos/area_do_cliente/public_html/',
 u'http://220.243.235.13/6843319.s21d-6.faiusrd.com/0/abuiabblgaag9qgfrwuoxeygnqe?f=a&%5cu0005&wsiphost=local',
 u'http://get.ddlmedia1012.info/downloadmanager/get?clickid=y810ifrcxc',
 u'http://shatteredrealities.net/support/activate/information/11d37cf69e7e159ddfc549a51ca901c8/login.php',
 u'http://scholigoneon.org.cy/dropboxdocument/b642ffe1dd813bc5d6590a66ad16927c/',
 u'http://acharefacil.com.br/app/webroot/js/latestfnb/',
 u'http://usherandson.com/news/wp-content/plugins/jetpack/views/hotmail2/security.html',
 u'http://paypal1.com.case.507-917-425.jjfqmrbi5n76yw.pwx4qurtj2t.com.ve/cgi-bin/webscr/',
 u'http://malkarafestival.com/images/bottom.gif/?184ff=398332',
 u'http://purvanchalseva.in/wp-content/upgrade/images/applen/apple-en/en/978913f1b016db9fe72a4dcf841a98f4/',
 u'http://www.marcinderegowski.pl/content/galeria/11/0/min/d72